version: '2'
services:
  gibd_zook:
    container_name: zookeeper
    image: gibdfrcu/zookeeper:alpine
    ports:
      - "2181:2181"
  gibd_kafk:
    container_name: kafka
    #build: ./kafka
    image: gibdfrcu/kafka:alpine
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "testo:1:1"
      KAFKA_ZOOKEEPER_CONNECT: gibd_zook:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gibd_nimb:
    container_name: storm-nimbus
    image: gibdfrcu/storm-nimbus:alpine
    ports:
      - "3773:3773"
      - "3772:3772"
      - "6627:6627"
    links: 
      - gibd_zook:zk
  gibd_supv:
    command: env
    container_name: storm-supervisor
    image: gibdfrcu/storm-supervisor:alpine
    ports:
      - "8000:8000"
    links: 
      - gibd_nimb:nimbus
      - gibd_zook:zk
  gibd_stui:
    container_name: storm-ui
    image: gibdfrcu/storm-ui:alpine
    ports:
      - "8080:8080"
    links: 
      - gibd_nimb:nimbus
      - gibd_zook:zk

