sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build -t anapsix/alpine-java 8/current/server-jre/standard/

script:
  - docker run -it --rm anapsix/alpine-java java -version
